/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#311400',
        'on-primary-container': '#fefcff',
        'surface-dim': '#cbdbf5',
        surface: '#f8f9ff',
        'tertiary-fixed': '#ffdcc6',
        'secondary-container': '#6063ee',
        background: '#f8f9ff',
        'secondary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'error-container': '#ffdad6',
        'surface-container-highest': '#d3e4fe',
        'surface-container-low': '#eff4ff',
        'surface-bright': '#f8f9ff',
        'on-error': '#ffffff',
        'outline-variant': '#c2c6d6',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#723600',
        'surface-variant': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-tertiary': '#ffffff',
        outline: '#727785',
        'inverse-on-surface': '#eaf1ff',
        'on-tertiary-container': '#fffbff',
        'primary-container': '#2170e4',
        tertiary: '#924700',
        'tertiary-fixed-dim': '#ffb786',
        'surface-tint': '#005ac2',
        'surface-container-high': '#dce9ff',
        'on-primary': '#ffffff',
        'inverse-primary': '#adc6ff',
        'on-error-container': '#93000a',
        primary: '#0058be',
        'surface-container': '#e5eeff',
        'on-secondary': '#ffffff',
        'inverse-surface': '#213145',
        'on-primary-fixed-variant': '#004395',
        'on-surface-variant': '#424754',
        'primary-fixed': '#d8e2ff',
        error: '#ba1a1a',
        'on-secondary-container': '#fffbff',
        'on-secondary-fixed': '#07006c',
        'secondary-fixed-dim': '#c0c1ff',
        'tertiary-container': '#b75b00',
        'on-secondary-fixed-variant': '#2f2ebe',
        'on-background': '#0b1c30',
        secondary: '#4648d4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '24px',
        base: '4px',
        sm: '8px',
        xs: '4px',
        'container-width': '360px',
        lg: '16px',
        md: '12px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-sm': ['16px', { lineHeight: '22px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
